# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bank_pb2 as bank__pb2


class BankStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Withdraw = channel.unary_unary(
                '/Bank/Withdraw',
                request_serializer=bank__pb2.GeneralRequest.SerializeToString,
                response_deserializer=bank__pb2.GeneralReply.FromString,
                )
        self.Deposit = channel.unary_unary(
                '/Bank/Deposit',
                request_serializer=bank__pb2.GeneralRequest.SerializeToString,
                response_deserializer=bank__pb2.GeneralReply.FromString,
                )
        self.Query = channel.unary_unary(
                '/Bank/Query',
                request_serializer=bank__pb2.GeneralRequest.SerializeToString,
                response_deserializer=bank__pb2.QueryReply.FromString,
                )
        self.BranchDeposit = channel.unary_unary(
                '/Bank/BranchDeposit',
                request_serializer=bank__pb2.BranchRequest.SerializeToString,
                response_deserializer=bank__pb2.BranchResponse.FromString,
                )
        self.BranchWithdraw = channel.unary_unary(
                '/Bank/BranchWithdraw',
                request_serializer=bank__pb2.BranchRequest.SerializeToString,
                response_deserializer=bank__pb2.BranchResponse.FromString,
                )


class BankServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BranchDeposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BranchWithdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=bank__pb2.GeneralRequest.FromString,
                    response_serializer=bank__pb2.GeneralReply.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=bank__pb2.GeneralRequest.FromString,
                    response_serializer=bank__pb2.GeneralReply.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=bank__pb2.GeneralRequest.FromString,
                    response_serializer=bank__pb2.QueryReply.SerializeToString,
            ),
            'BranchDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.BranchDeposit,
                    request_deserializer=bank__pb2.BranchRequest.FromString,
                    response_serializer=bank__pb2.BranchResponse.SerializeToString,
            ),
            'BranchWithdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.BranchWithdraw,
                    request_deserializer=bank__pb2.BranchRequest.FromString,
                    response_serializer=bank__pb2.BranchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bank(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/Withdraw',
            bank__pb2.GeneralRequest.SerializeToString,
            bank__pb2.GeneralReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/Deposit',
            bank__pb2.GeneralRequest.SerializeToString,
            bank__pb2.GeneralReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/Query',
            bank__pb2.GeneralRequest.SerializeToString,
            bank__pb2.QueryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BranchDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/BranchDeposit',
            bank__pb2.BranchRequest.SerializeToString,
            bank__pb2.BranchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BranchWithdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bank/BranchWithdraw',
            bank__pb2.BranchRequest.SerializeToString,
            bank__pb2.BranchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
