# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbank.proto\"E\n\x0cGeneralReply\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x12\n\nexecutions\x18\x03 \x01(\t\"M\n\x0eGeneralRequest\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\x12\r\n\x05\x63lock\x18\x04 \x01(\x05\"R\n\nQueryReply\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x05\x12\x12\n\nexecutions\x18\x04 \x01(\t\"9\n\rBranchRequest\x12\r\n\x05money\x18\x01 \x01(\x05\x12\r\n\x05\x63lock\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\"D\n\x0e\x42ranchResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x63lock\x18\x02 \x01(\x05\x12\x12\n\nexecutions\x18\x03 \x01(\t2\xf3\x01\n\x04\x42\x61nk\x12,\n\x08Withdraw\x12\x0f.GeneralRequest\x1a\r.GeneralReply\"\x00\x12+\n\x07\x44\x65posit\x12\x0f.GeneralRequest\x1a\r.GeneralReply\"\x00\x12\'\n\x05Query\x12\x0f.GeneralRequest\x1a\x0b.QueryReply\"\x00\x12\x32\n\rBranchDeposit\x12\x0e.BranchRequest\x1a\x0f.BranchResponse\"\x00\x12\x33\n\x0e\x42ranchWithdraw\x12\x0e.BranchRequest\x1a\x0f.BranchResponse\"\x00\x62\x06proto3'
)




_GENERALREPLY = _descriptor.Descriptor(
  name='GeneralReply',
  full_name='GeneralReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='GeneralReply.interface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='GeneralReply.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executions', full_name='GeneralReply.executions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=83,
)


_GENERALREQUEST = _descriptor.Descriptor(
  name='GeneralRequest',
  full_name='GeneralRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='GeneralRequest.interface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='GeneralRequest.money', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='GeneralRequest.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='GeneralRequest.clock', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=162,
)


_QUERYREPLY = _descriptor.Descriptor(
  name='QueryReply',
  full_name='QueryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='QueryReply.interface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='QueryReply.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='QueryReply.money', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executions', full_name='QueryReply.executions', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=246,
)


_BRANCHREQUEST = _descriptor.Descriptor(
  name='BranchRequest',
  full_name='BranchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='money', full_name='BranchRequest.money', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='BranchRequest.clock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='BranchRequest.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=305,
)


_BRANCHRESPONSE = _descriptor.Descriptor(
  name='BranchResponse',
  full_name='BranchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='BranchResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='BranchResponse.clock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executions', full_name='BranchResponse.executions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=375,
)

DESCRIPTOR.message_types_by_name['GeneralReply'] = _GENERALREPLY
DESCRIPTOR.message_types_by_name['GeneralRequest'] = _GENERALREQUEST
DESCRIPTOR.message_types_by_name['QueryReply'] = _QUERYREPLY
DESCRIPTOR.message_types_by_name['BranchRequest'] = _BRANCHREQUEST
DESCRIPTOR.message_types_by_name['BranchResponse'] = _BRANCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralReply = _reflection.GeneratedProtocolMessageType('GeneralReply', (_message.Message,), {
  'DESCRIPTOR' : _GENERALREPLY,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:GeneralReply)
  })
_sym_db.RegisterMessage(GeneralReply)

GeneralRequest = _reflection.GeneratedProtocolMessageType('GeneralRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERALREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:GeneralRequest)
  })
_sym_db.RegisterMessage(GeneralRequest)

QueryReply = _reflection.GeneratedProtocolMessageType('QueryReply', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREPLY,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:QueryReply)
  })
_sym_db.RegisterMessage(QueryReply)

BranchRequest = _reflection.GeneratedProtocolMessageType('BranchRequest', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:BranchRequest)
  })
_sym_db.RegisterMessage(BranchRequest)

BranchResponse = _reflection.GeneratedProtocolMessageType('BranchResponse', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHRESPONSE,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:BranchResponse)
  })
_sym_db.RegisterMessage(BranchResponse)



_BANK = _descriptor.ServiceDescriptor(
  name='Bank',
  full_name='Bank',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=378,
  serialized_end=621,
  methods=[
  _descriptor.MethodDescriptor(
    name='Withdraw',
    full_name='Bank.Withdraw',
    index=0,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Deposit',
    full_name='Bank.Deposit',
    index=1,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='Bank.Query',
    index=2,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_QUERYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BranchDeposit',
    full_name='Bank.BranchDeposit',
    index=3,
    containing_service=None,
    input_type=_BRANCHREQUEST,
    output_type=_BRANCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BranchWithdraw',
    full_name='Bank.BranchWithdraw',
    index=4,
    containing_service=None,
    input_type=_BRANCHREQUEST,
    output_type=_BRANCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANK)

DESCRIPTOR.services_by_name['Bank'] = _BANK

# @@protoc_insertion_point(module_scope)
